bugfix in shared_projects push/pull
 On branch master

	renamed:    bin/rsync_append.sh -> bin/pull_shared_projects
	modified:   bin/push_shared_projects

diff --git a/bin/pull_shared_projects b/bin/pull_shared_projects
--- a/bin/pull_shared_projects
+++ b/bin/pull_shared_projects
@@ -1,9 +1,37 @@
 #!/bin/bash
-THISDIR="$(cd `dirname "$0"` && pwd)"
-ROOTDIR="$( dirname "$THISDIR" )"
-LIBDIR="$ROOTDIR/lib"
 
-source "$LIBDIR/utils.sh"
+fail () {
+	echo "$@" >&2
+	exit 1
+}
+
+ensure_dir () {
+    if ! [ -d "$1" ]; then
+        mkdir -p -- "$1" || fail "couldn't create $1"
+    fi
+}
+
+rsync_append () {
+    local src="$1"
+    local dest="$2"
+    local logfile="$3"
+
+    if [ -z "$logfile" ]; then
+        fail "$0: logfile is a required argument"
+    fi
+
+    rsync \
+        --recursive \
+        --links \
+        --perms \
+        --times \
+        --owner \
+        --progress \
+        --human-readable \
+        --log-file="$logfile" \
+        -e 'ssh -p 2575' \
+        "$src/" "$dest/" || fail "$0: rsync failed"
+}
 
 logdir="$HOME/.saklogs"
 ensure_dir "$logdir"
@@ -12,4 +40,4 @@ logfile="$logdir/pull.log"
 src="fwpusers@saks.fireworksproject.com:~/shared_projects"
 dest="$( pwd )"
 
-"$THISDIR/rsync_append.sh" "$src" "$dest" "$logfile"
+rsync_append "$src" "$dest" "$logfile"
